services:
  weatherapp:
    build: .
    image: testimage
    ports:
      - "8000:8000"
    environment:
      API_KEY: "your_api_key"
      FLAGS_instanceID: "your_instance_id"
      FLAGS_URL: "https://flags.example.com"
      FLAGS_APP: "weatherapp"
      BG_COLOR: "yellow"
      APP_VERSION: "1.0.0"
