name: CI - Features/* branches
on:
  push:
    branches:
      - features/*
    paths-ignore:
      - "**/*.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_REPO }}/test-image

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install -r ./web_app/tests/requirements.txt
    - run: pytest ./web_app/tests/

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}


    - name: Build and Publish image
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: |
        docker compose up --build -d
        docker push ${DOCKER_IMAGE}:${GITHUB_SHA}


    - name: Reachability
      run: |
        for i in {1..10}; do
            status_code=$(curl --silent --output /dev/null --write-out "%{http_code}" http://localhost:8000)
            if [ "${status_code}" == 200 ]; then
                echo "Rechability Success, continue"
                exit 0
            fi
            sleep 5
        done
        echo "Rechability failed, for debugging look for ${{ github.sha }} image tag"
        exit 1