name: CI - Features/* branches
on:
  push:
    branches:
      - features/*
    paths-ignore:
      - "**/*.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_REPO }}/test-image

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install runner dependencies for tests 
      run: pip install -r ./web_app/tests/requirements.txt

    - name: Running tests 
      run: pytest ./web_app/tests/test_parse.py

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}


    - name: Build and Publish image
      env:
        GITHUB_SHA: ${{ github.sha }}
      run: |
        docker compose up --build -d
        docker push ${DOCKER_IMAGE}:${GITHUB_SHA}
        echo "for debugging look for ${GITHUB_SHA} image tag"


    - name: Reachability
      run: pytest ./web_app/tests/test_response.py