name: GitOps - Main Branch
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    - name: Get Version
      run: |
        VERSION=$(yq e '.services.weatherapp.environment.APP_VERSION' compose.yaml)
        echo "NEW_VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Set up Git
      run: |
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "CI Bot"

    - name: Clone GitOps repo
      run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/argocd.git
          cd argocd
          yq e -i '.APP_VERSION = "${{ env.NEW_VERSION }}"' weatherapp/helm/values.yaml
          git add weatherapp/helm/values.yaml
          git commit -m "Update weatherapp APP_VERSION to ${{ env.NEW_VERSION }}"
          git push origin main